### ISSUE TITLE
build fails with SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by nandoflorestan** [athif23/start-imba#29]
For a project created with parcel:

```
SyntaxError: Unexpected token 'export'
    at new Script (node:vm:100:7)
    at NativeCompileCache._moduleCompile (/home/nando/py/jobs/fairsplit/fair/fair/klient/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/nando/py/jobs/fairsplit/fair/fair/klient/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (/home/nando/py/jobs/fairsplit/fair/fair/klient/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/nando/py/jobs/fairsplit/fair/fair/klient/node_modules/imba/index.js:3:18)
    at Module._compile (/home/nando/py/jobs/fairsplit/fair/fair/klient/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

```

**Comment by nandoflorestan** [comment]
For a project created with webpack:

```
ERROR in multi ./source/index.imba ./source/index.css ./source/index.html
Module not found: Error: Can't resolve 'imba/loader' in '/home/nando/py/jobs/fairsplit/fair/fair/klient'
 @ multi ./source/index.imba ./source/index.css ./source/index.html main[0]

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./source/index.imba ./source/index.css ./source/index.html
Module not found: Error: Can't resolve 'imba/loader' in '/home/nando/py/jobs/fairsplit/fair/fair/klient'
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./source/index.imba ./source/index.css ./source/index.html main[1]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./source/index.html] 431 bytes {0} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!source/index.css:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js!./source/components/app.css] 1.1 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/cjs.js!./source/index.css] 529 bytes {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/runtime/api.js] 2.46 KiB {mini-css-extract-plugin} [built]
ℹ ｢wdm｣: Failed to compile.
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, stat '/home/nando/.steampath'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/nando/.steampath'
}

```

**Comment by nandoflorestan** [comment]
It is likely that this project is deprecated... I see imba offers this functionality itself:
https://imba.io/language/getting-started

If that's the case, then this should be explained prominently in the README

**Comment by webbrain-one** [comment]
Hi there! 👋

I've opened a pull request to address this build failure: https://github.com/athif23/start-imba/pull/63

This PR resolves the `SyntaxError: Unexpected token 'export'` error that occurs when building projects with Parcel. Let me know if you have any questions or feedback!
